# File: .gitlab-ci.yml
# Description: File to configure our Gitlab CI

# Stages
stages:
  - download
  - build
  - install
  - unit-test
  - integration-test
  - linting

.lb-setup: &lb-setup
  - module load cmake
  - module load gcc/10.2 openmpi/4.0
  - module load petsc/3.14
  - module load libnetcdf/4.7

cuas-dowload:
  stage: download
  tags:
    - general
  before_script: *lb-setup
  variables:
    GIT_STRATEGY: clone
  script:
    echo "repository cloned"

build-cuas:
  stage: build
  tags:
    - general
  before_script: *lb-setup
  variables:
    GIT_STRATEGY: none
  script:
    - cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DPETSC_DIR=$PETSC_ROOT -DNETCDF_DIR=$LIBNETCDF_ROOT
    - cmake --build build --verbose --parallel $(cat /proc/cpuinfo | grep processor | wc -l)

install-cuas:
  stage: install
  tags:
    - general
  before_script: *lb-setup
  variables:
    GIT_STRATEGY: none
  script:
    cmake --install build --prefix install

test-petscwrapper:
  stage: unit-test
  tags:
    - general
  before_script: *lb-setup
  variables:
    GIT_STRATEGY: none
  script:
    - cd install/test/petscwrapper/unit
    - mpirun -n 5 --timeout 60 ./test-PETScVector
    - mpirun -n 5 --timeout 60 ./test-PETScMatrix
    - mpirun -n 4 --timeout 60 ./test-PETScSolver
    - mpirun -n 4 --timeout 60 ./test-PETScGrid
    - mpirun -n 4 --timeout 60 ./test-fillgrid

test-cuascore:
  stage: unit-test
  tags:
    - general
  before_script: *lb-setup
  variables:
    GIT_STRATEGY: none
  script:
    - cd install/test/cuascore/unit
    - mpirun -n 1 --timeout 60 ./test-CUASArgs
    - mpirun -n 1 --timeout 60 ./test-timeparse
    - mpirun -n 9 --timeout 60 ./test-CUASKernels
    - mpirun -n 6 --timeout 60 ./test-specialgradient
    - mpirun -n 6 --timeout 60 ./test-forcing
    - mpirun -n 1 --timeout 60 ./test-systemmatrix
    - mpirun -n 4 --timeout 60 ./test-systemmatrix
    - mpirun -n 6 --timeout 60 ./test-fillNoData
    - mpirun -n 1 --timeout 60 ./test-NetCDFFile
    - mpirun -n 2 --timeout 60 ./test-NetCDFFile
    - mpirun -n 3 --timeout 60 ./test-NetCDFFile
    - mpirun -n 4 --timeout 60 ./test-NetCDFFile
    - mpirun -n 4 --timeout 60 ./test-SolutionHandler
    - mpirun -n 4 --timeout 60 ./test-initialHead
    #- mpirun -n 1 --timeout 60 ./test-ModelReader
    #- mpirun -n 1 --timeout 60 ./test-timeForcingNetcdf

test-cuas:
  stage: integration-test
  tags:
    - general
  before_script: *lb-setup
  variables:
    GIT_STRATEGY: none
  script:
    - cd install/test/cuascore/integration
    - mpirun -n 9 --timeout 60 ./test-noData
    # argc,argv test
    - mpirun -n 2 --timeout 60 ./test-exactTransientSolution
    - mpirun -n 2 --timeout 60 ./test-exactTransientSolution 1000.0
    - mpirun -n 2 --timeout 60 ./test-exactTransientSolution 1000.0 31
    - mpirun -n 2 --timeout 60 ./test-exactTransientSolution 1000.0 31 31
    - mpirun -n 2 --timeout 60 ./test-exactTransientSolution 1000.0 31 31 11
    - mpirun -n 2 --timeout 60 ./test-exactTransientSolution 1000.0 31 31 31 86400
    - mpirun -n 2 --timeout 60 ./test-exactTransientSolution 1000.0 31 31 31 86400 exactTransientSolution.nc
    # runs for science no output
    - mpirun -n 4 --timeout 60 ./test-exactTransientSolution 1000.0 101 101 31 86400
    - mpirun -n 4 --timeout 60 ./test-exactTransientSolution    1.0 101 101 31 86400
    # steady-state solution
    - mpirun -n 2 --timeout 60 ./test-exactSteadySolution
    # grid refinement example, Lx = Ly = 100km
    - mpirun -n 4 --timeout 60 ./test-exactSteadySolution 2000.0  51  51 31 86400
    - mpirun -n 4 --timeout 60 ./test-exactSteadySolution 1000.0 101 101 31 86400
    - mpirun -n 4 --timeout 60 ./test-exactSteadySolution  500.0 201 201 31 86400

run-clang-format:
  stage: linting
  tags:
    - general
  before_script:
    - *lb-setup
    - module load gcc llvm/12.0.1
  variables:
    GIT_STRATEGY: none
  script:
    - ./utils/checkClangFormat.sh

run-clang-tidy:
  stage: linting
  tags:
    - general
  before_script:
    - *lb-setup
    - module load gcc llvm/12.0.1
  variables:
    GIT_STRATEGY: none
  script:
    - ./utils/checkClangTidy.sh

run-cmake-format:
  stage: linting
  tags:
    - general
  before_script:
    - *lb-setup
    - module load python/3.9.5
  variables:
    GIT_STRATEGY: none
  script:
    - ./utils/checkCmakeFormat.sh
