# File: .gitlab-ci.yml
# Description: File to configure our Gitlab CI

# Stages
stages:
  - download
  - build-deps
  - build
  - unit-test
  - integration-test
  - install

.lb-setup: &lb-setup
  - eval $(ssh-agent -s)
  - ssh-add ~/.ssh/gitlab_rsa
  - export TUDA_SC_MODULES_ROOT="$DA_SC/moduletree/modules"
  - module use $TUDA_SC_MODULES_ROOT
  - export TUDA_ADDITIONAL_MODULEPATH=$TUDA_SC_MODULES_ROOT
  - export TUDA_SC_ISSM_MODULES_ROOT="$ISSM_PROJECT_DIR/moduletree/modules"
  - module use $TUDA_SC_ISSM_MODULES_ROOT
  - export TUDA_ADDITIONAL_MODULEPATH=$TUDA_ADDITIONAL_MODULEPATH:$TUDA_SC_ISSM_MODULES_ROOT
  - export TUDA_SC_ADDITIONAL_MODULEPATH=$TUDA_SC_ISSM_MODULES_ROOT
  - module load cmake gcc/10.2 openmpi/4.0 petsc/3.14
  - module load libnetcdf/4.7

.lb-tear-down: &lb-tear-down
  - echo $SSH_AUTH_SOCK
  - rm -rf $(dirname $(echo $SSH_AUTH_SOCK))
  - ssh-agent -k

cuas-dowload:
  stage: download
  tags:
    - general
  before_script: *lb-setup
  variables:
    GIT_STRATEGY: clone
  script:
    - *lb-tear-down

build-cuas:
  stage: build
  tags:
    - general
  before_script: *lb-setup
  variables:
    GIT_STRATEGY: none
  script:
    - rm -rf build && mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TEST=ON -DPETSC_DIR=$PETSC_ROOT -DNETCDF_DIR=$LIBNETCDF_ROOT ..
    - make -j $(cat /proc/cpuinfo | grep processor | wc -l)
    - *lb-tear-down

test-petscwrapper:
  stage: unit-test
  tags:
    - general
  before_script: *lb-setup
  variables:
    GIT_STRATEGY: none
  script:
    - cd build/test/petscwrapper/unit
    - mpirun -n 5 --timeout 10 ./test-PETScVector
    - mpirun -n 5 --timeout 10 ./test-PETScMatrix
    - mpirun -n 4 --timeout 10 ./test-PETScSolver
    - mpirun -n 4 --timeout 10 ./test-PETScGrid

test-cuascore:
  stage: unit-test
  tags:
    - general
  before_script: *lb-setup
  variables:
    GIT_STRATEGY: none
  script:
    - cd build/test/cuascore/unit
    - ./test-CUASArgs
    - ./test-timeparse
    - mpirun -n 9 --timeout 10 ./test-CUASKernels
    - mpirun -n 6 --timeout 10 ./test-specialgradient
    - mpirun -n 6 --timeout 60 ./test-forcing
    - mpirun -n 1 --timeout 10 ./test-systemmatrix
    - mpirun -n 6 --timeout 60 ./test-fillNoData
    - mpirun -n 1 --timeout 60 ./test-NetCDFFile
    - mpirun -n 2 --timeout 60 ./test-NetCDFFile
    - mpirun -n 3 --timeout 60 ./test-NetCDFFile
    - mpirun -n 4 --timeout 60 ./test-NetCDFFile
    - mpirun -n 4 --timeout 60 ./test-SolutionHandler
    #- ./test-ModelReader

test-cuas:
  stage: integration-test
  tags:
    - general
  before_script: *lb-setup
  variables:
    GIT_STRATEGY: none
  script:
    - cd build/test/cuascore/integration
    - mpirun -n 9 --timeout 60 ./test-noData

