# File: .gitlab-ci.yml
# Description: File to configure our Gitlab CI

# Stages
stages:
  - download
  - build
  - install
  - unit-test
  - integration-test

.lb-setup: &lb-setup
  - module load cmake
  - module load gcc/10.2 openmpi/4.0
  - module load petsc/3.14
  - module load libnetcdf/4.7

cuas-dowload:
  stage: download
  tags:
    - general
  before_script: *lb-setup
  variables:
    GIT_STRATEGY: clone
  script:
    echo "repository cloned"

build-cuas:
  stage: build
  tags:
    - general
  before_script: *lb-setup
  variables:
    GIT_STRATEGY: none
  script:
    - cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DPETSC_DIR=$PETSC_ROOT -DNETCDF_DIR=$LIBNETCDF_ROOT
    - cmake --build build --verbose --parallel $(cat /proc/cpuinfo | grep processor | wc -l)

install-cuas:
  stage: install
  tags:
    - general
  before_script: *lb-setup
  variables:
    GIT_STRATEGY: none
  script:
    cmake --install build --prefix install

test-petscwrapper:
  stage: unit-test
  tags:
    - general
  before_script: *lb-setup
  variables:
    GIT_STRATEGY: none
  script:
    - cd install/test/petscwrapper/unit
    - mpirun -n 5 --timeout 10 ./test-PETScVector
    - mpirun -n 5 --timeout 10 ./test-PETScMatrix
    - mpirun -n 4 --timeout 10 ./test-PETScSolver
    - mpirun -n 4 --timeout 10 ./test-PETScGrid

test-cuascore:
  stage: unit-test
  tags:
    - general
  before_script: *lb-setup
  variables:
    GIT_STRATEGY: none
  script:
    - cd install/test/cuascore/unit
    - ./test-CUASArgs
    - ./test-timeparse
    - mpirun -n 9 --timeout 10 ./test-CUASKernels
    - mpirun -n 6 --timeout 10 ./test-specialgradient
    - mpirun -n 6 --timeout 60 ./test-forcing
    - mpirun -n 1 --timeout 10 ./test-systemmatrix
    - mpirun -n 6 --timeout 60 ./test-fillNoData
    - mpirun -n 1 --timeout 60 ./test-NetCDFFile
    - mpirun -n 2 --timeout 60 ./test-NetCDFFile
    - mpirun -n 3 --timeout 60 ./test-NetCDFFile
    - mpirun -n 4 --timeout 60 ./test-NetCDFFile
    - mpirun -n 4 --timeout 60 ./test-SolutionHandler
    - mpirun -n 4 --timeout 10 ./test-initialHead
    #- ./test-ModelReader

test-cuas:
  stage: integration-test
  tags:
    - general
  before_script: *lb-setup
  variables:
    GIT_STRATEGY: none
  script:
    - cd install/test/cuascore/integration
    - mpirun -n 9 --timeout 60 ./test-noData

